services:
#  mariadb:
#    image: 'mariadb:latest'
#    environment:
#      - 'MARIADB_DATABASE=mydatabase'
#      - 'MARIADB_PASSWORD=secret'
#      - 'MARIADB_ROOT_PASSWORD=verysecret'
#      - 'MARIADB_USER=myuser'
#    ports:
#      - '3306'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=employee'
      - 'POSTGRES_PASSWORD=employee2025'
      - 'POSTGRES_USER=employee'
    ports:
      - '5432'
